### ISSUE TITLE
Wrong SO_URL in action.config for Coleco

### ISSUE THREAD

**Issue by ITCactus** [clockworkpi/Menu#1]
there is an issue with ["SO_URL" for action.config for Coleco](https://github.com/clockworkpi/Menu/blob/2d75a8d65dda71092460668811d90980c12154bb/20_Retro%20Games/60_Coleco/action.config#L6)
it should be changed to
`SO_URL=https://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest/bluemsx_libretro.so.zip`
because existed in the config URL is not accessible.
also, it's preventing setup emulator from the Launcher.
see [my post on the forum](https://forum.clockworkpi.com/t/how-to-setup-bluemsx-for-colecovision/3155/11?u=itcactus)

**Comment by cuu** [comment]
thanks

**Comment by cuu** [comment]
fixed a182be1
